# -*- coding: utf-8 -*-
"""heart_disease_assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxzFrARoBsUmaFt-4cdRrWF1Noyd8ReC
"""

!pip install fuzzy

from fuzzy_logic import compute_risk
from utils import validate_input

def get_user_input():
    inputs = {}

    inputs['age'] = validate_input("Enter age (e.g., 30-90): ", 30, 90)
    inputs['sex'] = validate_input("Enter sex (0 = female, 1 = male): ", 0, 1)
    inputs['cp'] = validate_input("Enter chest pain type (0-3): ", 0, 3)
    inputs['trestbps'] = validate_input("Enter resting blood pressure: ", 80, 200)
    inputs['chol'] = validate_input("Enter cholesterol level: ", 100, 600)
    inputs['fbs'] = validate_input("Enter fasting blood sugar (0 = False, 1 = True): ", 0, 1)
    inputs['restecg'] = validate_input("Enter resting ECG results (0-2): ", 0, 2)
    inputs['thalach'] = validate_input("Enter max heart rate achieved: ", 60, 220)
    inputs['exang'] = validate_input("Enter exercise-induced angina (0 = No, 1 = Yes): ", 0, 1)
    inputs['oldpeak'] = validate_input("Enter oldpeak value (ST depression): ", 0.0, 6.0)
    inputs['slope'] = validate_input("Enter slope of ST segment (0-2): ", 0, 2)
    inputs['ca'] = validate_input("Enter number of major vessels (0-3): ", 0, 3)
    inputs['thal'] = validate_input("Enter thalassemia type (0-3): ", 0, 3)

    return inputs

if __name__ == "__main__":
    user_data = get_user_input()
    risk_level = compute_risk(**user_data)
    print(f"\nHeart Disease Risk Level: {risk_level}")