# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Lk9Cf-GHe6HphvwXZuN5YRByxy0OjCu
"""

def validate_input(prompt, min_value, max_value):
    while True:
        try:
            value = float(input(prompt))
            if min_value <= value <= max_value:
                return value
            else:
                print(f"Error: Value must be between {min_value} and {max_value}.")
        except ValueError:
            print("Error: Please enter a valid number.")